data objetsSas ;
  set listefile ;
  length typeObjet $10 ;
  typeObjet = "";*lowcase(type) ;
  if lowcase(type) eq "sas" then typeObjet = "Programme" ;
  else if lowcase(type) eq 'sct01' then typeObjet = "Catalog" ;
  else if lowcase(type) eq 'ssp01' then typeObjet = "Stored Process";
  else if lowcase(type) eq 'ssd01' then typeObjet = "DataSet" ;
  else if lowcase(type) eq 'snx01' then typeObjet = "Index" ;
  else if lowcase(type) eq 'ssm01' then typeObjet = "Cube" ;
  else if lowcase(type) eq 'ssv01' then typeObjet = "Vue" ;
  else if lowcase(type) eq 'ssa01' then typeObjet = "Access View";
  if (typeObjet ne "") then output ;
run ;
